audioFiles=[
{filename: "banjo.wav", note:"C"},
{filename: "clavinet.wav", note:"C"},
{filename: "hooknows.wav", note:"C"},
{filename: "hoverboard.wav", note:"C", volume:0.5},
{filename: "hurtsmyears.wav", note:"C", volume: 0.5},
{filename: "ohyeahharp.wav", note:"C"},
{filename: "palmmute.wav", note:"C"},
{filename: "shocking.wav", note:"C", volume:0.2},
{filename: "snapster.wav", note:"C"},
{filename: "squarebaby.wav", note:"C", volume:0.3},
{filename: "steeldrum.wav", note:"C"},
{filename: "synthpiano.wav", note:"C", volume:0.7},
{filename: "tickbell.wav", note:"C"},
{filename: "honkytonk.wav", note:"C", volume:1}];