audioFiles=[
{filename: "banjo", note:"C"},
{filename: "clavinet", note:"C"},
{filename: "hooknows", note:"C"},
{filename: "hoverboard", note:"C", volume:0.5},
{filename: "hurtsmyears", note:"C", volume: 0.5},
{filename: "ohyeahharp", note:"C"},
{filename: "palmmute", note:"C"},
{filename: "shocking", note:"C", volume:0.2},
{filename: "snapster", note:"C"},
{filename: "squarebaby", note:"C", volume:0.3},
{filename: "steeldrum", note:"C"},
{filename: "synthpiano", note:"C", volume:0.7},
{filename: "tickbell", note:"C"},
{filename: "honkytonk", note:"C", volume:1}];